#!/usr/bin/env python
#coding:utf-8

import sys
import re
import os

argvs = sys.argv
argc = len(argvs)

if (argc != 4):
    print("4 arguments is needed")
    quit()

target_filename= argvs[1]
pattern = argvs[2]
target =  open(target_filename,"r+")
insertfile =  open(argvs[3])

target_txt = target.readlines()
insert_txt = str.rstrip(insertfile.read())

tmp_filename = 'tmp_file000'
tmp_file = open(tmp_filename,'w+')

print(argvs[3])

print("pattern : " + pattern)
for line in target_txt:
    tmp_file.write(re.sub(re.compile(pattern),insert_txt,line))
print(tmp_file)
os.rename(tmp_filename,target_filename)
